361Capstone/361Capstone/Controllers/ProductDetailsController.cs
using _361Capstone.Models;
using _361Capstone.Managers;
using _361Capstone.Accessors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

namespace _361Capstone.Controllers
{
    public class ProductDetailsController : Controller
    {
        ProductsManager manager = new ProductsManager();

        // Returns default index page for the product details page
        // that shows an end user the specific details about a product.
        public IActionResult Index(int productId, int userId, int addedItem) {
            Product product = manager.GetProduct(productId);

            //Validates the session to ensure lists can only be edited by the user they belong to.
            SessionManager Sessionmgr = new SessionManager();
            string key = HttpContext.Session.GetString("_Key");
            if (!Sessionmgr.ValidateKey(key, userId)) {
                return RedirectToAction("Logout", "Login");
            }

            ViewData["Title"] = product.GetName();
            ViewData["ProductName"] = product.GetName();
            ViewData["Description"] = product.GetDescription();
            ViewData["ManInfo"] = product.GetManInfo();
            ViewData["Dimensions"] = product.GetDimensions();
            ViewData["Weight"] = product.GetWeight();
            ViewData["Rating"] = product.GetRating();
            ViewData["StockCount"] = product.GetStockCount();
            ViewData["UserId"] = userId;
            ViewData["ProductId"] = product.GetProductId();
            ViewData["AddedItem"] = addedItem;
            ViewData["Price"] = product.GetPrice();

            return View();
        }

        // The add to cart button runs this script that adds the product
        // being viewed to the user's cart.
        public IActionResult AddItemToCart(int userId, int productId, int count) {
            CartProductAccessor accessor = new CartProductAccessor();
            int addedItem = 0;

            bool returnVal = accessor.InsertCartProduct(userId, productId, count);

            if(returnVal) {
                addedItem = 1;
            } else {
                addedItem = -1;
            }

            return RedirectToAction("Index", new { productId, userId, addedItem });
        }

    }
}

361Capstone/361Capstone/Views/ProductDetails/Index.cshtml
@{
    Layout = "_Layout";

    ViewBag.Title = ViewData["Title"];

}
@using _361Capstone.Models;

<html>

<head>

    <link href="@Url.Content("~/CSS/List.css")" rel="stylesheet" type="text/css" asp-append-version="true" />
    <script src="@Url.Content("~/Content/Scripts/jquery-3.6.0.min.js")"></script>


</head>

<body>

    <div style="display:none" id="addSuccess" class="alert alert-success" role="alert">
        This item was successfully added to your cart.
    </div>
    <div style="display:none" id="addFail" class="alert alert-danger" role="alert">
        Error: There was a problem adding this item to your cart.
    </div>
    <a style="float:right;margin-left:5px" class="btn btn-danger" href="@Url.Action("Logout", "Login")" role="button">Log out</a>
    <a style="float:right" class="btn btn-primary" href="@Url.Action("Index", "UserCart", new { userId = ViewData["UserId"] })" role="button">View Cart</a>
    <div class="grid-container">


        <div class="list">

            <h1>@ViewData["Title"]</h1>
            <h4><strong>Price:</strong> $@ViewData["Price"]</h4>
            <p><strong>Description:</strong> @ViewData["Description"]</p>
            <p><strong>Manufacturer Info:</strong> @ViewData["ManInfo"]</p>
            <p><strong>Dimensions:</strong> @ViewData["Dimensions"]</p>
            <p><strong>Weight:</strong> @ViewData["Weight"]lbs</p>
            <p><strong>Rating:</strong> @ViewData["Rating"]</p>
            <p><strong>Amount in Stock:</strong> @ViewData["StockCount"]</p>

            <!--Lists items-->
            <!--For loop to add spaces-->
            <ul style="list-style-type:none;" class="space">
            </ul>
        </div>

        <div class="addToCart">
            <form autocomplete="off">
                <hr />
                <!--<label for="username"><b>Username</b></label>
                <input type="text" class="txtInput" id="username" placeholder="Enter Username"><br>

                <label for="password"><b>Password</b></label>
                <input type="password" class="txtInput" id="password" placeholder="Enter Password"><br>-->
                <!--<label for="itemQuantity">Add items to cart: </label>-->
                <input type="number" id="quantity" name="itemQuantity" min="1" max='@ViewData["StockCount"]' value="1" />
                <input type="button" class="submitBtn" id="submitBtn" value="Add to Cart" onclick="addItemToCart(@ViewData["UserId"], @ViewData["ProductId"], document.getElementById('quantity').value)"><br>
            </form>
            <br /><br />
            <a class="btn btn-primary" href='@Url.Action("Index", "Products")?userId=@ViewData["UserId"]' role="button">Go To Products Page</a>
        </div>

    </div>
</body>
</html>

<script>

    function checkForAddedItem() {
        var addedItemBool = @ViewData["AddedItem"];
        if (addedItemBool == 1) {
            $('#addSuccess').show();
        } else if(addedItemBool == -1) {
            $('#addFail').show();
        }
    }

    $(document).ready(function () {
        $('#addSuccess', '#addFail').hide();

        checkForAddedItem();
    })



    function addItemToCart(userId, productId, count) {
        location.href = '@Url.Action("AddItemToCart", "ProductDetails")?userId=' + userId + '&productId=' + productId + "&count=" + count;
    }
</script>