361Capstone/361Capstone/Controllers/InsertDataController.cs
using _361Capstone.Managers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace _361Capstone.Controllers {
    public class InsertDataController : Controller {
        private SessionManager SessionMgr { get; set; } = new SessionManager();
        private InsertDataManager manager = new InsertDataManager();

        // Returns the default index page to the page where users
        // must input payment and address info to be tied to their account.
        public IActionResult Index(int userId) {

            string key = HttpContext.Session.GetString("_Key");
            if (!SessionMgr.ValidateKey(key, userId)) {
                return RedirectToAction("Logout", "Login");
            }

            ViewData["UserId"] = userId;


            return View();
        }

        // When fired, this script sends the data inserted by the user on the
        // page to the database to be tied to their account.
        public IActionResult SendData(int userId, string ccn, int expm, int expy, 
                                      int cvv, string street, string city, string state, 
                                      int zip, string country) {

            manager.SendPaymentInfo(userId, ccn, expm, expy, cvv);
            manager.SendAddress(userId, street, city, state, zip, country);
            return RedirectToAction("Index", "Checkout", new { userId });
        }

    }
}

361Capstone/361Capstone/Views/InsertData/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@using _361Capstone.Managers;
@using System.Web;
<html>
<head>
    
       <title>Insert Data</title>
</head>
<body>
    <div class="alert alert-info" role="alert">
        Our records show that you do not have any address/payment information! Please input the needed information to continue to check out.
    </div>
    <a style="float:right;margin-left:5px" class="btn btn-danger" href="@Url.Action("Logout", "Login")" role="button">Log out</a>
    <form>
        <div class="paymentInfo">
            <h3>Payment Information</h3>
            <label for="creditCardNumber"><b>Credit Card Number: </b></label>
            <input type="text" id="creditCardNumber" name="creditCardNumber" />
            <br />
            <label for="expMonth"><b>Expiration Month: </b></label>
            <input type="number" id="expMonth" min="1" max="12" name="expMonth" />
            <br />
            <label for="expYear"><b>Expiration Year: </b></label>
            <input type="number" id="expYear" min="2020" max="2999" name="expYear" />
            <br />
            <label for="cvvCode"><b>CVV Code: </b></label>
            <input type="number" id="cvvCode" min="1" max="999" name="cvvCode" />
        </div>
        <hr />
        <div class="addressInfo">
            <h3>Address Information</h3>
            <label for="street"><b>Street: </b></label>
            <input type="text" name="street" id="street" />
            <br />
            <label for="city"><b>City: </b></label>
            <input type="text" name="city" id="city" />
            <br />
            <label for="state"><b>State: </b></label>
            <input type="text" name="state" id="state" />
            <br />
            <label for="zipCode"><b>Zip Code: </b></label>
            <input type="text" name="zipCode" id="zipCode" />
            <br />
            <label for="country"><b>Country: </b></label>
            <input type="text" name="country" id="country" />
        </div>
    </form>
    <br />
    <a class="btn btn-success" role="button" onclick="
    sendData(@ViewData["UserId"], document.getElementById('creditCardNumber').value,
        document.getElementById('expMonth').value,
        document.getElementById('expYear').value, document.getElementById('cvvCode').value,
        document.getElementById('street').value, document.getElementById('city').value,
        document.getElementById('state').value, document.getElementById('zipCode').value,
        document.getElementById('country').value)
    ">Save & Continue</a>



</body>
</html>

<script>
    function sendData(userId, ccn, expm, expy, cvv, street, city, state, zip, country) {
        location.href = '@Url.Action("SendData", "InsertData")?userId=' + userId + '&ccn=' + ccn
            + "&expm=" + expm + "&expy=" + expy + "&cvv=" + cvv + "&street=" + street
            + "&city=" + city + "&state=" + state + "&zip=" + zip + "&country=" + country;
    }

</script>